name: Deploy Frontend (Next.js) to GCP VM

on:
  push:
    branches:
      - main
      - staging

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  REGION: ${{ vars.REGION }}
  REPOSITORY: ${{ vars.REPOSITORY }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  CODE_ENV: ${{ vars.CODECAMP }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ----------------------
      # Checkout code
      # ----------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ----------------------
      # Generate image tag
      # ----------------------
      - name: Generate Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV